use std::fs;
use std::path::PathBuf;
use std::process::Command;

use crate::state::expand_path;
use crate::wallpaper::run_cmd;

pub const SUPPORTED: &[&str] =
	&["waybar", "swaync", "niri", "kitty", "yazi", "walker", "nvim", "btop", "fish"];

// Маркер авто-генерируемого скрипта. Пока он есть в файле — скрипт считается
// управляемым программой и перезаписывается из шаблона при его изменении (после
// обновления программы). Удалите строку-маркер — файл станет «кастомным» и больше
// никогда не будет перезаписан.
pub const GEN_MARKER: &str = "# ASWADPFTLS-GENERATED";

// Полный список ролей палитры — порядок неважен, используется в циклах генерации
// CSS-файлов (waybar, swaync, walker).
const ROLES: &str = "ROSEWATER FLAMINGO PINK MAUVE RED MAROON PEACH YELLOW GREEN \
TEAL SKY SAPPHIRE BLUE LAVENDER TEXT SUBTEXT1 SUBTEXT0 OVERLAY2 OVERLAY1 OVERLAY0 \
SURFACE2 SURFACE1 SURFACE0 BASE MANTLE CRUST";

pub fn script_template(name: &str, palette_path: &str) -> String {
	let header = format!(
		"#!/usr/bin/env fish\n\
         {GEN_MARKER} — авто-генерируется из шаблона, не редактировать.\n\
         # Чтобы кастомизировать: удалите строку-маркер выше (файл перестанет перезаписываться).\n\
         source {palette_path}\n\n"
	);
	match name {
		"waybar" => format!(
			"{header}\
mkdir -p ~/.config/waybar
set out ~/.config/waybar/colors.css
echo -n > $out

for role in {ROLES}
    set color_name COLOR_$role
    set color $$color_name
    printf \"@define-color %s %s;\\n\" (string lower $role) $color >> $out
    # on-цвет: читаемый текст, когда роль используется как фон
    set on_name \"COLOR_\"$role\"_ON\"
    set on $$on_name
    printf \"@define-color %s_on %s;\\n\" (string lower $role) $on >> $out
end
"
		),
		// swaync импортирует общий ~/.config/colors/colors.css (см. его style.css)
		"swaync" => format!("{header}{SWAYNC}"),
		"kitty" => format!("{header}{KITTY}"),
		"yazi" => format!("{header}{YAZI}"),
		"walker" => format!("{header}{WALKER}"),
		"nvim" => format!("{header}{NVIM}"),
		"btop" => format!("{header}{BTOP}"),
		"niri" => format!("{header}{NIRI}"),
		"fish" => format!("{header}{FISH}"),
		_ => unreachable!(),
	}
}

// swaync: генерируем общий CSS-файл с палитрой, который его style.css уже
// импортирует (@import "../colors/colors.css"). Формат тот же, что у waybar.
// Живая перезагрузка через swaync-client, без рестарта сервиса.
const SWAYNC: &str = r#"mkdir -p ~/.config/colors
set out ~/.config/colors/colors.css
echo -n > $out
for role in ROSEWATER FLAMINGO PINK MAUVE RED MAROON PEACH YELLOW GREEN TEAL SKY SAPPHIRE BLUE LAVENDER TEXT SUBTEXT1 SUBTEXT0 OVERLAY2 OVERLAY1 OVERLAY0 SURFACE2 SURFACE1 SURFACE0 BASE MANTLE CRUST
    set cname COLOR_$role
    set color $$cname
    set on_name "COLOR_"$role"_ON"
    set on $$on_name
    printf '@define-color %s %s;\n' (string lower $role) $color >> $out
    printf '@define-color %s_on %s;\n' (string lower $role) $on >> $out
end
echo "swaync: $out"
swaync-client --reload-css 2>/dev/null; or true
"#;

// kitty: colors.conf (kitty.conf уже делает `include colors.conf`).
// SIGUSR1 перезагружает конфиг во всех открытых окнах без перезапуска.
const KITTY: &str = r#"mkdir -p ~/.config/kitty
set out ~/.config/kitty/colors.conf
printf '%s\n\n' '# generated by ASWaDPFTLS — не редактировать вручную' > $out
printf 'background %s\nforeground %s\n' $COLOR_BASE $COLOR_TEXT >> $out
printf 'cursor %s\ncursor_text_color %s\n' $COLOR_ROSEWATER $COLOR_BASE >> $out
printf 'selection_background %s\nselection_foreground %s\n' $COLOR_SURFACE2 $COLOR_TEXT >> $out
printf 'url_color %s\n\n' $COLOR_BLUE >> $out
printf 'color0 %s\ncolor8 %s\n' $COLOR_SURFACE1 $COLOR_SURFACE2 >> $out
printf 'color1 %s\ncolor9 %s\n' $COLOR_RED $COLOR_RED >> $out
printf 'color2 %s\ncolor10 %s\n' $COLOR_GREEN $COLOR_GREEN >> $out
printf 'color3 %s\ncolor11 %s\n' $COLOR_YELLOW $COLOR_YELLOW >> $out
printf 'color4 %s\ncolor12 %s\n' $COLOR_BLUE $COLOR_BLUE >> $out
printf 'color5 %s\ncolor13 %s\n' $COLOR_PINK $COLOR_PINK >> $out
printf 'color6 %s\ncolor14 %s\n' $COLOR_TEAL $COLOR_TEAL >> $out
printf 'color7 %s\ncolor15 %s\n' $COLOR_SUBTEXT1 $COLOR_SUBTEXT0 >> $out
echo "kitty: $out"
pkill -SIGUSR1 -x kitty 2>/dev/null; or true
"#;

// walker: GTK-CSS тема. Цвета выносим в colors.css каталога темы, а в style.css
// вырезаем встроенные @define-color и добавляем @import — layout/правила целы.
// Имя темы берём из config.toml (ключ `theme`).
const WALKER: &str = r#"set wconf ~/.config/walker/config.toml
if not test -f $wconf
    echo "walker: нет config.toml — пропуск"
    exit 0
end
set theme (grep -oP '^\s*theme\s*=\s*"\K[^"]+' $wconf | head -n1)
test -z "$theme"; and set theme default
set tdir ~/.config/walker/themes/$theme
mkdir -p $tdir
set out $tdir/colors.css
echo -n > $out
for role in ROSEWATER FLAMINGO PINK MAUVE RED MAROON PEACH YELLOW GREEN TEAL SKY SAPPHIRE BLUE LAVENDER TEXT SUBTEXT1 SUBTEXT0 OVERLAY2 OVERLAY1 OVERLAY0 SURFACE2 SURFACE1 SURFACE0 BASE MANTLE CRUST
    set cname COLOR_$role
    set color $$cname
    printf '@define-color %s %s;\n' (string lower $role) $color >> $out
end
set style $tdir/style.css
if test -f $style
    sed -i -E '/^\s*@define-color/d; /@import url\("colors\.css"\)/d' $style
    sed -i '1i @import url("colors.css");' $style
end
echo "walker: $out (тема $theme)"
"#;

// yazi: цвета нельзя импортировать из theme.toml, поэтому генерируем native-флейвор
// и переключаем theme.toml на него. Старый theme.toml сохраняем в .bak (один раз).
const YAZI: &str = r#"set fdir ~/.config/yazi/flavors/aswadpftls.yazi
mkdir -p $fdir
set out $fdir/flavor.toml
begin
printf '%s\n\n' '# generated by ASWaDPFTLS'
printf '[manager]\n'
printf 'cwd = { fg = "%s", bold = true }\n' $COLOR_BLUE
printf 'hovered = { fg = "%s", bg = "%s" }\n' $COLOR_BASE $COLOR_BLUE
printf 'preview_hovered = { underline = true }\n'
printf 'find_keyword = { fg = "%s", bold = true, underline = true }\n' $COLOR_YELLOW
printf 'find_position = { fg = "%s", bold = true }\n' $COLOR_MAUVE
printf 'marker_copied = { fg = "%s", bg = "%s" }\n' $COLOR_GREEN $COLOR_GREEN
printf 'marker_cut = { fg = "%s", bg = "%s" }\n' $COLOR_RED $COLOR_RED
printf 'marker_marked = { fg = "%s", bg = "%s" }\n' $COLOR_TEAL $COLOR_TEAL
printf 'marker_selected = { fg = "%s", bg = "%s" }\n' $COLOR_LAVENDER $COLOR_LAVENDER
printf 'count_copied = { fg = "%s", bg = "%s" }\n' $COLOR_BASE $COLOR_GREEN
printf 'count_cut = { fg = "%s", bg = "%s" }\n' $COLOR_BASE $COLOR_RED
printf 'count_selected = { fg = "%s", bg = "%s" }\n' $COLOR_BASE $COLOR_LAVENDER
printf 'tab_active = { fg = "%s", bg = "%s", bold = true }\n' $COLOR_TEXT $COLOR_SURFACE0
printf 'tab_inactive = { fg = "%s", bg = "%s" }\n' $COLOR_OVERLAY0 $COLOR_MANTLE
printf 'border_symbol = "|"\n'
printf 'border_style = { fg = "%s" }\n\n' $COLOR_SURFACE1
printf '[status]\n'
printf 'separator_style = { fg = "%s", bg = "%s" }\n' $COLOR_SURFACE0 $COLOR_MANTLE
printf 'normal_main = { fg = "%s", bg = "%s", bold = true }\n' $COLOR_BASE $COLOR_BLUE
printf 'normal_alt = { fg = "%s", bg = "%s" }\n' $COLOR_TEXT $COLOR_SURFACE1
printf 'select_main = { fg = "%s", bg = "%s", bold = true }\n' $COLOR_BASE $COLOR_GREEN
printf 'select_alt = { fg = "%s", bg = "%s" }\n' $COLOR_TEXT $COLOR_SURFACE1
printf 'unset_main = { fg = "%s", bg = "%s", bold = true }\n' $COLOR_BASE $COLOR_MAUVE
printf 'unset_alt = { fg = "%s", bg = "%s" }\n' $COLOR_TEXT $COLOR_SURFACE1
printf 'progress_label = { fg = "%s", bold = true }\n' $COLOR_TEXT
printf 'progress_normal = { fg = "%s", bg = "%s" }\n' $COLOR_BLUE $COLOR_MANTLE
printf 'progress_error = { fg = "%s", bg = "%s" }\n' $COLOR_RED $COLOR_MANTLE
printf 'perm_type = { fg = "%s" }\n' $COLOR_OVERLAY0
printf 'perm_read = { fg = "%s" }\n' $COLOR_GREEN
printf 'perm_write = { fg = "%s" }\n' $COLOR_RED
printf 'perm_exec = { fg = "%s" }\n\n' $COLOR_PEACH
printf '[select]\n'
printf 'border = { fg = "%s" }\n' $COLOR_BLUE
printf 'active = { fg = "%s", bold = true }\n' $COLOR_MAUVE
printf 'inactive = { fg = "%s" }\n\n' $COLOR_OVERLAY0
printf '[input]\n'
printf 'border = { fg = "%s" }\n' $COLOR_BLUE
printf 'title = { fg = "%s", bold = true }\n' $COLOR_LAVENDER
printf 'value = { fg = "%s" }\n' $COLOR_TEXT
printf 'selected = { fg = "%s", bg = "%s" }\n\n' $COLOR_BASE $COLOR_BLUE
printf '[completion]\n'
printf 'border = { fg = "%s" }\n' $COLOR_BLUE
printf 'active = { fg = "%s", bold = true }\n' $COLOR_MAUVE
printf 'inactive = { fg = "%s" }\n\n' $COLOR_OVERLAY0
printf '[tasks]\n'
printf 'border = { fg = "%s" }\n' $COLOR_BLUE
printf 'title = { fg = "%s", bold = true }\n' $COLOR_LAVENDER
printf 'hovered = { underline = true }\n\n'
printf '[which]\n'
printf 'mask = { bg = "%s" }\n' $COLOR_MANTLE
printf 'cand = { fg = "%s" }\n' $COLOR_SKY
printf 'rest = { fg = "%s" }\n' $COLOR_OVERLAY0
printf 'desc = { fg = "%s" }\n' $COLOR_MAUVE
printf 'separator = "  "\n'
printf 'separator_style = { fg = "%s" }\n\n' $COLOR_SURFACE1
printf '[help]\n'
printf 'on = { fg = "%s" }\n' $COLOR_MAUVE
printf 'run = { fg = "%s" }\n' $COLOR_BLUE
printf 'desc = { fg = "%s" }\n' $COLOR_SUBTEXT0
printf 'hovered = { fg = "%s", bg = "%s" }\n' $COLOR_BASE $COLOR_BLUE
printf 'footer = { fg = "%s", bg = "%s" }\n' $COLOR_BASE $COLOR_LAVENDER
end > $out
echo "yazi: flavor → $out"

set tconf ~/.config/yazi/theme.toml
if not test -f $tconf; or not grep -qE '^\[flavor\]' $tconf
    test -f $tconf; and cp $tconf $tconf.bak; and echo "yazi: бэкап старого theme.toml → $tconf.bak"
    printf '[flavor]\ndark = "aswadpftls"\nlight = "aswadpftls"\n' > $tconf
    echo "yazi: theme.toml переключён на flavor aswadpftls"
end
"#;

// nvim: Lua-модуль палитры lua/aswadpftls_palette.lua, возвращающий таблицу
// { имя_цвета_catppuccin = "#hex" }. Имена ролей совпадают с палитрой Catppuccin
// Mocha, поэтому модуль скармливается напрямую в color_overrides.mocha — все
// интеграции (treesitter, telescope, lsp, gitsigns, lualine) сохраняются.
// init.lua подключает его сам (pcall require), здесь его не трогаем.
// Чистим скомпилированный кэш catppuccin, чтобы новые цвета подхватились при
// следующем запуске nvim (catppuccin не отслеживает изменения внешнего файла).
const NVIM: &str = r#"mkdir -p ~/.config/nvim/lua
set out ~/.config/nvim/lua/aswadpftls_palette.lua
begin
printf '%s\n' '-- generated by ASWaDPFTLS — палитра для catppuccin color_overrides.mocha'
printf 'return {\n'
printf '  rosewater = "%s",\n' $COLOR_ROSEWATER
printf '  flamingo = "%s",\n' $COLOR_FLAMINGO
printf '  pink = "%s",\n' $COLOR_PINK
printf '  mauve = "%s",\n' $COLOR_MAUVE
printf '  red = "%s",\n' $COLOR_RED
printf '  maroon = "%s",\n' $COLOR_MAROON
printf '  peach = "%s",\n' $COLOR_PEACH
printf '  yellow = "%s",\n' $COLOR_YELLOW
printf '  green = "%s",\n' $COLOR_GREEN
printf '  teal = "%s",\n' $COLOR_TEAL
printf '  sky = "%s",\n' $COLOR_SKY
printf '  sapphire = "%s",\n' $COLOR_SAPPHIRE
printf '  blue = "%s",\n' $COLOR_BLUE
printf '  lavender = "%s",\n' $COLOR_LAVENDER
printf '  text = "%s",\n' $COLOR_TEXT
printf '  subtext1 = "%s",\n' $COLOR_SUBTEXT1
printf '  subtext0 = "%s",\n' $COLOR_SUBTEXT0
printf '  overlay2 = "%s",\n' $COLOR_OVERLAY2
printf '  overlay1 = "%s",\n' $COLOR_OVERLAY1
printf '  overlay0 = "%s",\n' $COLOR_OVERLAY0
printf '  surface2 = "%s",\n' $COLOR_SURFACE2
printf '  surface1 = "%s",\n' $COLOR_SURFACE1
printf '  surface0 = "%s",\n' $COLOR_SURFACE0
printf '  base = "%s",\n' $COLOR_BASE
printf '  mantle = "%s",\n' $COLOR_MANTLE
printf '  crust = "%s",\n' $COLOR_CRUST
printf '}\n'
end > $out
echo "nvim: $out (catppuccin color_overrides.mocha)"
rm -rf ~/.cache/nvim/catppuccin 2>/dev/null; or true
"#;

// btop: генерируем тему themes/aswadpftls.theme (формат theme[key]="#hex") и
// переключаем color_theme в btop.conf. btop читает тему при запуске — рестарт
// не шлём, новый цвет подхватится при следующем открытии.
const BTOP: &str = r#"mkdir -p ~/.config/btop/themes
set out ~/.config/btop/themes/aswadpftls.theme
begin
printf '%s\n' '# generated by ASWaDPFTLS'
printf 'theme[main_bg]="%s"\n' $COLOR_BASE
printf 'theme[main_fg]="%s"\n' $COLOR_TEXT
printf 'theme[title]="%s"\n' $COLOR_TEXT
printf 'theme[hi_fg]="%s"\n' $COLOR_BLUE
printf 'theme[selected_bg]="%s"\n' $COLOR_SURFACE0
printf 'theme[selected_fg]="%s"\n' $COLOR_TEXT
printf 'theme[inactive_fg]="%s"\n' $COLOR_OVERLAY0
printf 'theme[graph_text]="%s"\n' $COLOR_SUBTEXT0
printf 'theme[meter_bg]="%s"\n' $COLOR_SURFACE0
printf 'theme[proc_misc]="%s"\n' $COLOR_MAUVE
printf 'theme[cpu_box]="%s"\n' $COLOR_OVERLAY0
printf 'theme[mem_box]="%s"\n' $COLOR_OVERLAY0
printf 'theme[net_box]="%s"\n' $COLOR_OVERLAY0
printf 'theme[proc_box]="%s"\n' $COLOR_OVERLAY0
printf 'theme[div_line]="%s"\n' $COLOR_SURFACE1
printf 'theme[temp_start]="%s"\n' $COLOR_GREEN
printf 'theme[temp_mid]="%s"\n' $COLOR_YELLOW
printf 'theme[temp_end]="%s"\n' $COLOR_RED
printf 'theme[cpu_start]="%s"\n' $COLOR_SKY
printf 'theme[cpu_mid]="%s"\n' $COLOR_BLUE
printf 'theme[cpu_end]="%s"\n' $COLOR_MAUVE
printf 'theme[free_start]="%s"\n' $COLOR_GREEN
printf 'theme[free_mid]="%s"\n' $COLOR_GREEN
printf 'theme[free_end]="%s"\n' $COLOR_GREEN
printf 'theme[cached_start]="%s"\n' $COLOR_BLUE
printf 'theme[cached_mid]="%s"\n' $COLOR_BLUE
printf 'theme[cached_end]="%s"\n' $COLOR_BLUE
printf 'theme[available_start]="%s"\n' $COLOR_TEAL
printf 'theme[available_mid]="%s"\n' $COLOR_TEAL
printf 'theme[available_end]="%s"\n' $COLOR_TEAL
printf 'theme[used_start]="%s"\n' $COLOR_PEACH
printf 'theme[used_mid]="%s"\n' $COLOR_RED
printf 'theme[used_end]="%s"\n' $COLOR_RED
printf 'theme[download_start]="%s"\n' $COLOR_GREEN
printf 'theme[download_mid]="%s"\n' $COLOR_GREEN
printf 'theme[download_end]="%s"\n' $COLOR_GREEN
printf 'theme[upload_start]="%s"\n' $COLOR_PEACH
printf 'theme[upload_mid]="%s"\n' $COLOR_PEACH
printf 'theme[upload_end]="%s"\n' $COLOR_RED
printf 'theme[process_start]="%s"\n' $COLOR_GREEN
printf 'theme[process_mid]="%s"\n' $COLOR_BLUE
printf 'theme[process_end]="%s"\n' $COLOR_MAUVE
printf 'theme[battery_start]="%s"\n' $COLOR_GREEN
printf 'theme[battery_mid]="%s"\n' $COLOR_YELLOW
printf 'theme[battery_end]="%s"\n' $COLOR_RED
end > $out
echo "btop: $out"
set conf ~/.config/btop/btop.conf
if test -f $conf
    if grep -qE '^color_theme' $conf
        sed -i -E 's|^color_theme.*|color_theme = "aswadpftls"|' $conf
    else
        printf 'color_theme = "aswadpftls"\n' >> $conf
    end
else
    printf 'color_theme = "aswadpftls"\n' > $conf
end
echo "btop: color_theme → aswadpftls"
"#;

// niri: цвета зашиты в config.kdl (active-gradient/active-color/urgent-color),
// импорта внешних файлов у KDL нет — правим точечным sed по ключам. Якорь ^\s*
// важен, чтобы active-* не цеплялся за inactive-*; inactive/shadow не трогаем
// (прозрачность/тень остаются как есть). Бэкап один раз. niri сам live-reload'ит.
const NIRI: &str = r#"set conf ~/.config/niri/config.kdl
if not test -f $conf
    echo "niri: нет config.kdl — пропуск"
    exit 0
end
test -f "$conf.bak"; or cp $conf "$conf.bak"
sed -i -E 's|^(\s*active-gradient from=")[^"]*(" to=")[^"]*|\1'$COLOR_BLUE'\2'$COLOR_LAVENDER'|' $conf
sed -i -E 's|^(\s*active-color ")[^"]*|\1'$COLOR_BLUE'|' $conf
sed -i -E 's|^(\s*urgent-color ")[^"]*|\1'$COLOR_RED'|' $conf
echo "niri: active/urgent цвета обновлены в $conf"
"#;

// fish: подсветка синтаксиса и pager задаются переменными fish_color_* /
// fish_pager_color_*. Пишем их в universal-область (set -U): значения перекрывают
// остатки прежней темы (Catppuccin и т.п. ставят те же переменные universal) и
// СРАЗУ применяются ко всем запущенным сессиям fish — живое обновление без
// перезапуска, как у kitty/swaync. Прежний conf.d-файл (подход set -g) удаляем:
// глобальная область затеняла бы universal в новых сессиях и расходилась бы с тем,
// что видят уже открытые терминалы.
//
// ВАЖНО: # отрезаем (string replace). Несмотря на то, что set_color принимает
// hex с #, в позиции отдельного аргумента `#rrggbb` fish трактует как начало
// комментария — значение терялось бы. Поэтому пишем голый hex, как принято в
// конфигах fish. Имя переменной перед --background/--bold останавливает разбор
// опций builtin set, поэтому эти флаги воспринимаются как значение цвета.
const FISH: &str = r#"rm -f ~/.config/fish/conf.d/aswadpftls-colors.fish
set -U fish_color_normal (string replace '#' '' $COLOR_TEXT)
set -U fish_color_command (string replace '#' '' $COLOR_BLUE)
set -U fish_color_keyword (string replace '#' '' $COLOR_MAUVE)
set -U fish_color_quote (string replace '#' '' $COLOR_GREEN)
set -U fish_color_redirection (string replace '#' '' $COLOR_SKY)
set -U fish_color_end (string replace '#' '' $COLOR_YELLOW)
set -U fish_color_error (string replace '#' '' $COLOR_RED)
set -U fish_color_param (string replace '#' '' $COLOR_TEXT)
set -U fish_color_option (string replace '#' '' $COLOR_SKY)
set -U fish_color_comment (string replace '#' '' $COLOR_OVERLAY0)
set -U fish_color_operator (string replace '#' '' $COLOR_TEAL)
set -U fish_color_escape (string replace '#' '' $COLOR_PEACH)
set -U fish_color_cancel (string replace '#' '' $COLOR_RED)
set -U fish_color_autosuggestion (string replace '#' '' $COLOR_SURFACE2)
set -U fish_color_selection --background=(string replace '#' '' $COLOR_SURFACE0)
set -U fish_color_search_match (string replace '#' '' $COLOR_YELLOW) --background=(string replace '#' '' $COLOR_SURFACE1)
set -U fish_pager_color_prefix (string replace '#' '' $COLOR_LAVENDER) --bold
set -U fish_pager_color_completion (string replace '#' '' $COLOR_TEXT)
set -U fish_pager_color_description (string replace '#' '' $COLOR_OVERLAY0)
set -U fish_pager_color_progress (string replace '#' '' $COLOR_LAVENDER)
set -U fish_pager_color_secondary_prefix (string replace '#' '' $COLOR_SURFACE2)
set -U fish_pager_color_selected_background --background=(string replace '#' '' $COLOR_SURFACE0)
set -U fish_pager_color_selected_prefix (string replace '#' '' $COLOR_BLUE) --bold
echo "fish: цвета применены (universal, живое обновление всех сессий)"
"#;

pub fn is_systemd_service(name: &str) -> bool {
	Command::new("systemctl")
		.args(["--user", "is-active", "--quiet", name])
		.status()
		.map(|s| s.success())
		.unwrap_or(false)
}

pub fn restart_util(name: &str) {
	// niri сам подхватывает изменения цветов — ничего не делаем
	if name == "niri" {
		return;
	}

	if is_systemd_service(name) {
		match Command::new("systemctl").args(["--user", "restart", name]).output() {
			Ok(out) if out.status.success() => println!("{name} перезапущен через systemd"),
			Ok(out) => eprintln!("{name}: {}", String::from_utf8_lossy(&out.stderr).trim()),
			Err(e) => eprintln!("systemctl: {e}"),
		}
		return;
	}

	match name {
		"waybar" => eprintln!("waybar не запущен как systemd-сервис — перезапуск невозможен"),
		"swaync" => eprintln!("swaync не запущен как systemd-сервис — перезапуск невозможен"),
		_ => {}
	}
}

// kitty (SIGUSR1), swaync (swaync-client --reload-css), yazi/walker/nvim
// (подхватывают при следующем запуске) перезагружаются сами внутри скрипта —
// рестарт сервиса нужен только waybar.
pub fn needs_restart(name: &str) -> bool {
	matches!(name, "waybar")
}

// Что сделать с файлом скрипта перед запуском. Выделено отдельно, чтобы логику
// «кастомный / обновить / запустить как есть» можно было покрыть юнит-тестами без
// побочных эффектов (запуск fish, изменение конфигов утилит).
#[derive(Debug, PartialEq, Eq)]
pub enum ScriptPlan {
	/// Файл без маркера — кастомный скрипт пользователя, запускаем как есть.
	RunCustom,
	/// Записать содержимое (создать новый или обновить устаревший) и запустить.
	Write,
	/// Управляемый файл уже совпадает с шаблоном — просто запускаем.
	RunAsIs,
	/// Встроенного шаблона нет и кастомного файла тоже — генератора не существует.
	NoGenerator,
}

// existing — текущее содержимое файла (если есть); desired — содержимое из шаблона
// (Some только для встроенных утилит из SUPPORTED).
pub fn plan_script(existing: Option<&str>, desired: Option<&str>) -> ScriptPlan {
	match (existing, desired) {
		// Файл есть, но без нашего маркера — кастомный, не трогаем.
		(Some(c), _) if !c.contains(GEN_MARKER) => ScriptPlan::RunCustom,
		// Управляемый файл совпадает с шаблоном — ничего не пишем.
		(Some(c), Some(d)) if c == d => ScriptPlan::RunAsIs,
		// Управляемый файл устарел относительно шаблона / файла ещё нет.
		(_, Some(_)) => ScriptPlan::Write,
		// Управляемый файл есть, но шаблона для имени нет — просто запускаем.
		(Some(_), None) => ScriptPlan::RunAsIs,
		// Ни файла, ни шаблона.
		(None, None) => ScriptPlan::NoGenerator,
	}
}

// Создаёт заготовку кастомного генератора generation_<name>.fish. Файл намеренно
// БЕЗ маркера GEN_MARKER, поэтому программа его никогда не перезапишет. Палитра
// доступна через $ASWADPFTLS_PALETTE (его выставляет generate_and_run).
pub fn scaffold_custom_generator(
	scripts_dir: &str,
	name: &str,
) -> Result<PathBuf, Box<dyn std::error::Error>> {
	let dir = expand_path(scripts_dir);
	fs::create_dir_all(&dir)?;
	let script = dir.join(format!("generation_{name}.fish"));
	if script.exists() {
		return Err(format!("Файл уже существует: {}", script.display()).into());
	}
	let content = format!(
		"#!/usr/bin/env fish\n\
         # Кастомный генератор ASWaDPFTLS для «{name}».\n\
         # Здесь нет строки-маркера {GEN_MARKER}, поэтому программа НЕ перезапишет файл.\n\
         # Палитра обоев доступна через переменные $COLOR_* после source.\n\
         source $ASWADPFTLS_PALETTE\n\
         \n\
         # Доступные роли (есть также версии с суффиксом _ON — контрастный текст на фоне роли):\n\
         #   {ROLES}\n\
         #\n\
         # Пример:\n\
         #   mkdir -p ~/.config/{name}\n\
         #   printf 'background %s\\n' $COLOR_BASE > ~/.config/{name}/colors.conf\n\
         \n\
         echo \"{name}: TODO — заполните генератор (см. комментарии выше)\"\n"
	);
	fs::write(&script, &content)?;
	#[cfg(unix)]
	{
		use std::os::unix::fs::PermissionsExt;
		fs::set_permissions(&script, fs::Permissions::from_mode(0o755))?;
	}
	Ok(script)
}

pub fn generate_and_run(
	generation_conf: &[String],
	scripts_dir: &str,
	palette_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
	let dir = expand_path(scripts_dir);
	fs::create_dir_all(&dir)?;

	for name in generation_conf {
		let script = dir.join(format!("generation_{name}.fish"));
		let existing = fs::read_to_string(&script).ok();
		let desired =
			SUPPORTED.contains(&name.as_str()).then(|| script_template(name, palette_path));

		match plan_script(existing.as_deref(), desired.as_deref()) {
			ScriptPlan::RunCustom => {
				println!("Запуск (кастомный): {}", script.display());
			}
			ScriptPlan::Write => {
				// desired здесь всегда Some (иначе был бы NoGenerator/RunAsIs).
				let content = desired.as_deref().unwrap_or_default();
				fs::write(&script, content)?;
				#[cfg(unix)]
				{
					use std::os::unix::fs::PermissionsExt;
					fs::set_permissions(&script, fs::Permissions::from_mode(0o755))?;
				}
				println!(
					"{} скрипт: {}",
					if existing.is_some() { "Обновлён" } else { "Создан" },
					script.display()
				);
				println!("Запуск: {}", script.display());
			}
			ScriptPlan::RunAsIs => {
				println!("Запуск: {}", script.display());
			}
			ScriptPlan::NoGenerator => {
				eprintln!(
					"Нет генератора для '{name}'. Создайте кастомный:\n  \
                     aswadpftls new-generator {name}"
				);
				continue;
			}
		}

		// $ASWADPFTLS_PALETTE доступен и кастомным скриптам: source $ASWADPFTLS_PALETTE.
		let mut cmd = Command::new("fish");
		cmd.arg(&script).env("ASWADPFTLS_PALETTE", palette_path);
		run_cmd(&mut cmd, "fish")?;

		if needs_restart(name) {
			restart_util(name);
		}
	}

	Ok(())
}

#[cfg(test)]
mod tests {
	use super::*;
	use std::io::Write;

	// Логика выбора действия над файлом скрипта (без побочных эффектов).
	#[test]
	fn plan_script_decisions() {
		let managed = format!("{GEN_MARKER}\nsource x\necho hi\n");
		let managed_old = format!("{GEN_MARKER}\nsource x\necho OLD\n");
		let custom = "#!/usr/bin/env fish\necho мой скрипт\n";

		// Нет файла, есть шаблон → создать.
		assert_eq!(plan_script(None, Some(&managed)), ScriptPlan::Write);
		// Управляемый файл совпадает с шаблоном → запустить как есть.
		assert_eq!(plan_script(Some(&managed), Some(&managed)), ScriptPlan::RunAsIs);
		// Управляемый файл устарел (шаблон изменился) → перезаписать.
		assert_eq!(plan_script(Some(&managed_old), Some(&managed)), ScriptPlan::Write);
		// Кастомный файл (без маркера) → не трогать, даже если есть встроенный шаблон.
		assert_eq!(plan_script(Some(custom), Some(&managed)), ScriptPlan::RunCustom);
		// Кастомный файл и нет встроенного шаблона → запустить как есть.
		assert_eq!(plan_script(Some(custom), None), ScriptPlan::RunCustom);
		// Ни файла, ни шаблона → генератора нет.
		assert_eq!(plan_script(None, None), ScriptPlan::NoGenerator);
	}

	// Каждый шаблон должен быть синтаксически корректным fish-скриптом.
	#[test]
	fn templates_are_valid_fish() {
		for &name in SUPPORTED {
			let script = script_template(name, "~/.config/colors/palette.fish");
			let mut tmp = tempfile_with(&script);
			let out = Command::new("fish")
				.arg("-n")
				.arg(tmp.path())
				.output()
				.expect("fish должен быть установлен для теста");
			assert!(
				out.status.success(),
				"шаблон '{name}' содержит синтаксическую ошибку fish:\n{}",
				String::from_utf8_lossy(&out.stderr)
			);
			tmp.cleanup();
		}
	}

	struct Tmp(std::path::PathBuf);
	impl Tmp {
		fn path(&self) -> &std::path::Path { &self.0 }
		fn cleanup(&mut self) { let _ = fs::remove_file(&self.0); }
	}
	fn tempfile_with(content: &str) -> Tmp {
		let p = std::env::temp_dir().join(format!("aswadpftls_gen_{}.fish", std::process::id()));
		let mut f = fs::File::create(&p).unwrap();
		f.write_all(content.as_bytes()).unwrap();
		Tmp(p)
	}

	// Прогоняем шаблоны в песочнице ($HOME → tempdir) и проверяем, что они
	// создают ожидаемые файлы с подставленными цветами. Защищает от регрессий
	// в путях и формате вывода (не только в синтаксисе).
	#[test]
	fn templates_produce_expected_files() {
		let home = std::env::temp_dir().join(format!("asw_home_{}", std::process::id()));
		let _ = fs::remove_dir_all(&home);
		let cfg = home.join(".config");
		fs::create_dir_all(cfg.join("colors")).unwrap();
		let theme_dir = cfg.join("walker/themes/catppuccin_mocha");
		fs::create_dir_all(&theme_dir).unwrap();

		// Минимальный palette.fish: все роли + _ON, чтобы скрипты не падали.
		let mut pal = String::new();
		for role in ROLES.split_whitespace() {
			pal.push_str(&format!("set -gx COLOR_{role} \"#123456\"\n"));
			pal.push_str(&format!("set -gx COLOR_{role}_ON \"#ffffff\"\n"));
		}
		fs::write(cfg.join("colors/palette.fish"), pal).unwrap();

		// walker: тема с встроенным @define-color — он должен быть вырезан и заменён @import.
		fs::write(theme_dir.join("style.css"),
		          "* { all: unset; }\n@define-color old #000000;\n.foo { color: @text; }\n").unwrap();
		fs::write(cfg.join("walker/config.toml"), "theme = \"catppuccin_mocha\"\n").unwrap();

		// btop: существующий конфиг с другой темой — color_theme должен переключиться.
		fs::create_dir_all(cfg.join("btop")).unwrap();
		fs::write(cfg.join("btop/btop.conf"), "color_theme = \"catppuccin_mocha\"\ntheme_background = true\n").unwrap();

		// niri: блок border. inactive-gradient/inactive-color намеренно включены —
		// проверяем, что якорь ^\s* их НЕ трогает (active-* не цепляет inactive-*).
		fs::create_dir_all(cfg.join("niri")).unwrap();
		fs::write(cfg.join("niri/config.kdl"),
		          "border {\n    width 2\n    active-gradient from=\"#aaaaaa\" to=\"#bbbbbb\" angle=45\n    inactive-gradient from=\"#111111\" to=\"#222222\" angle=45\n    inactive-color \"#00000000\"\n    urgent-color \"#cccccc\"\n}\n").unwrap();

		// Песочница для universal-переменных fish (set -U в шаблоне fish): явно
		// переопределяем XDG_DATA_HOME/XDG_RUNTIME_DIR, чтобы fish_variables писались
		// в tempdir, а не в реальный стор пользователя при cargo test.
		let data_home = home.join(".local/share");
		let runtime_dir = home.join("run");
		fs::create_dir_all(&data_home).unwrap();
		fs::create_dir_all(&runtime_dir).unwrap();

		let palette_path = cfg.join("colors/palette.fish");
		let run = |name: &str| {
			let script = script_template(name, palette_path.to_str().unwrap());
			let sp = home.join(format!("gen_{name}.fish"));
			fs::write(&sp, script).unwrap();
			let out = Command::new("fish")
				.arg(&sp)
				.env("HOME", &home)
				.env("XDG_DATA_HOME", &data_home)
				.env("XDG_RUNTIME_DIR", &runtime_dir)
				.output()
				.expect("fish");
			assert!(out.status.success(),
			        "[{name}] упал:\n{}", String::from_utf8_lossy(&out.stderr));
		};

		run("kitty");
		let kitty = fs::read_to_string(cfg.join("kitty/colors.conf")).unwrap();
		assert!(kitty.contains("background #123456"), "kitty: нет background\n{kitty}");
		assert!(kitty.contains("color4 #123456"), "kitty: нет color4");

		run("swaync");
		let sw = fs::read_to_string(cfg.join("colors/colors.css")).unwrap();
		assert!(sw.contains("@define-color text #123456;"), "swaync: нет text\n{sw}");
		assert!(sw.contains("@define-color base_on #ffffff;"), "swaync: нет base_on");

		run("walker");
		let wcss = fs::read_to_string(theme_dir.join("colors.css")).unwrap();
		assert!(wcss.contains("@define-color blue #123456;"), "walker: нет blue");
		let wstyle = fs::read_to_string(theme_dir.join("style.css")).unwrap();
		assert!(wstyle.starts_with("@import url(\"colors.css\");"), "walker: нет @import:\n{wstyle}");
		assert!(!wstyle.contains("@define-color old"), "walker: старый @define-color не вырезан");

		run("yazi");
		let flavor = fs::read_to_string(cfg.join("yazi/flavors/aswadpftls.yazi/flavor.toml")).unwrap();
		assert!(flavor.contains("[manager]"), "yazi: нет [manager]\n{flavor}");
		assert!(flavor.contains("fg = \"#123456\""), "yazi: нет цвета");
		let ytheme = fs::read_to_string(cfg.join("yazi/theme.toml")).unwrap();
		assert!(ytheme.contains("dark = \"aswadpftls\""), "yazi: theme.toml не переключён");

		run("nvim");
		let nv = fs::read_to_string(cfg.join("nvim/lua/aswadpftls_palette.lua")).unwrap();
		assert!(nv.trim_start().starts_with("--"), "nvim: нет шапки\n{nv}");
		assert!(nv.contains("return {"), "nvim: нет return-таблицы");
		assert!(nv.contains("base = \"#123456\","), "nvim: нет base");
		assert!(nv.contains("blue = \"#123456\","), "nvim: нет blue");

		run("btop");
		let bt = fs::read_to_string(cfg.join("btop/themes/aswadpftls.theme")).unwrap();
		assert!(bt.contains("theme[main_bg]=\"#123456\""), "btop: нет main_bg\n{bt}");
		assert!(bt.contains("theme[cpu_start]=\"#123456\""), "btop: нет cpu_start");
		let btconf = fs::read_to_string(cfg.join("btop/btop.conf")).unwrap();
		assert!(btconf.contains("color_theme = \"aswadpftls\""), "btop: color_theme не переключён\n{btconf}");
		assert!(btconf.contains("theme_background = true"), "btop: затёрта остальная конфигурация");

		run("niri");
		let kdl = fs::read_to_string(cfg.join("niri/config.kdl")).unwrap();
		assert!(kdl.contains("active-gradient from=\"#123456\" to=\"#123456\" angle=45"),
		        "niri: active-gradient не обновлён\n{kdl}");
		assert!(kdl.contains("urgent-color \"#123456\""), "niri: urgent-color не обновлён");
		// Ключевая проверка: inactive-* остались нетронутыми.
		assert!(kdl.contains("inactive-gradient from=\"#111111\" to=\"#222222\""),
		        "niri: inactive-gradient ошибочно затронут\n{kdl}");
		assert!(kdl.contains("inactive-color \"#00000000\""), "niri: inactive-color ошибочно затронут");

		run("fish");
		// Прежний conf.d-файл (подход set -g) должен быть удалён шаблоном.
		assert!(!cfg.join("fish/conf.d/aswadpftls-colors.fish").exists(),
		        "fish: старый conf.d-файл не удалён");
		// Главная проверка: значения реально доходят до universal-переменных и
		// читаются новой сессией fish (та же песочница XDG_DATA_HOME). Заодно это
		// проверяет, что # отрезан (иначе `#123456` был бы принят за комментарий).
		let probe = Command::new("fish")
			.arg("-c")
			.arg("echo $fish_color_command ; echo $fish_color_selection ; echo $fish_pager_color_selected_prefix")
			.env("HOME", &home)
			.env("XDG_DATA_HOME", &data_home)
			.env("XDG_RUNTIME_DIR", &runtime_dir)
			.output()
			.unwrap();
		let vals = String::from_utf8_lossy(&probe.stdout);
		let mut lines = vals.lines();
		assert_eq!(lines.next(), Some("123456"), "fish: fish_color_command не дошёл до universal\nвывод:\n{vals}");
		assert_eq!(lines.next(), Some("--background=123456"), "fish: fish_color_selection неверен\n{vals}");
		assert_eq!(lines.next(), Some("123456 --bold"), "fish: pager selected_prefix неверен\n{vals}");

		let _ = fs::remove_dir_all(&home);
	}
}
